#!/bin/bash

#case $BLOCK_BUTTON in
	#1) pkill -RTMIN+6 i3blocks && notify-send "Doge refreshed";;
#esac

value=$(coinmon -f doge | grep "\|Coin" | sed "s/\s*//g ; s/─//g ; s/┼//g ; s/┤//g ; s/┘//g ; s/├//g ; s/└//g ; s/┴//g ; s/┬//g ; s/┐//g ; s/┌//g ; s/│/;/g ; s/^Data.*//g" | grep DOGE | awk -F';' '{print $4}' | cut -d'm' -f 2 | grep -Po "^[0-9]*\.[0-9]..." | awk '{print $1 " * 14918"}' | bc | cut -d'.' -f 1)

previous=$(cat ~/.cache/DogeValue)

if [ -z "$value" ]
then
	echo "🐶No Data"
else
	if [ $value -lt $previous ]
	then
		echo "🐶Rp.$value🔻"
	elif [ $value -gt $previous ]
	then
		echo "🐶Rp.$value🔺"
	else
		echo "🐶Rp.$value"
	fi
fi

echo "$value" > ~/.cache/DogeValue
