#!/bin/bash

# Define the file to store the monitor state
STATE_FILE="$HOME/.screenlayout/monitor_state"

# Function to get the status of external monitors
get_external_monitor_status() {
    xrandr | grep " connected" | grep -v eDP1 | awk '{ print $1 }'
}

# Get the list of connected external monitors
external_monitors=$(get_external_monitor_status)

# Read the current state from the state file (default to "0" if the file does not exist)
if [ -f "$STATE_FILE" ]; then
    monitor_state=$(cat "$STATE_FILE")
else
    monitor_state="0"
fi

if [ -z "$external_monitors" ]; then
    # No external monitors connected, default to laptop monitor
    xrandr --output eDP1 --mode 1920x1080 --pos 0x0 --rotate normal --output DP1 --off --output DP2 --off --output HDMI1 --off --output HDMI2 --off --output VIRTUAL1 --off
    echo "0" > "$STATE_FILE"
else
    # External monitor is connected, toggle between laptop and external monitor
    if [ "$monitor_state" == "1" ]; then
        xrandr --output eDP1 --mode 1920x1080 --pos 0x0 --rotate normal --output DP1 --off --output DP2 --off --output HDMI1 --off --output HDMI2 --off --output VIRTUAL1 --off
        echo "0" > "$STATE_FILE"
    else
        xrandr --output eDP1 --off --output DP1 --off --output DP2 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output HDMI1 --off --output HDMI2 --off --output VIRTUAL1 --off
        echo "1" > "$STATE_FILE"
    fi
fi
